DECLARE @sql nvarchar(max) = '
--CREATE OR ALTER VIEW rpt.VIEW_PM_GSS AS
WITH O1 AS (' + rpt.sqlPivotDCv2('LOG_GSS_PM_PARTS', default) + ')
, O2 AS (' + rpt.sqlPivotDCv2('LOG_GSS_PM', default) + ')
, H AS (
	SELECT TASK_ID, ACTIVITY_ID, EQP_ID, STARTED_BY, null AS COMPLETED_BY, SCHEDULED_TIME, STATUS, STARTED_TIME, null AS COMPLETION_TIME, EVENT_SEQ_ID
	FROM [dbo].[E_ES_TASK_DETAILS]
	UNION ALL
	SELECT TASK_ID, ACTIVITY_ID, EQP_ID, STARTED_BY, COMPLETED_BY, SCHEDULED_TIME, STATUS, STARTED_TIME, COMPLETION_TIME, OBJECT_SEQ_ID
	FROM [dbo].[E_ES_TASK_HIST_DETAILS]
)
SELECT H.EVENT_SEQ_ID
, H.ACTIVITY_ID
, H.EQP_ID
, H.STARTED_BY
, H.COMPLETED_BY
, H.SCHEDULED_TIME
, H.STATUS
, H.STARTED_TIME
, H.COMPLETION_TIME
, A.OBJECT_ID as LOT_ID
, O1.GraphiteORing
, O1.HeaterTape
, O1.Thermocouple
, O1.BallValve
, O1.FilterCandle
, O1.SwageFitting
, O1.SanitaryFlange
, O1.Other
, O2.Qty as GSSCarbonQty
, O2.ToolState as PostPMState
, O2.Comments
--, O2.PERFORMED_DATE as GSSLogDate
FROM H
LEFT JOIN O1 ON H.TASK_ID = O1.COMPONENT_ID
AND RIGHT(O1.CURRENT_POSITION, CHARINDEX(''~'', REVERSE(O1.CURRENT_POSITION)) - 1) = H.EVENT_SEQ_ID
LEFT JOIN O2 ON H.TASK_ID = O2.COMPONENT_ID
AND RIGHT(O2.CURRENT_POSITION, CHARINDEX(''~'', REVERSE(O2.CURRENT_POSITION)) - 1) = H.EVENT_SEQ_ID
LEFT JOIN E_CS_ACTION_HISTORY A 
	ON O2.PERFORMED_DATE = A.ACTION_DATE 
	AND ACTION_TYPE = ''com.eyelit.view.StartLotView'' AND OBJECT_TYPE = ''MFDUNIT''
WHERE H.STATUS NOT IN (''DELETED'', ''ABORTED'')
--ORDER BY SCHEDULED_TIME DESC
';

EXEC sp_executesql @sql;



/** update alchemy */

DROP TABLE IF EXISTS rpt.mv_Sample;
SELECT * INTO rpt.mv_Sample FROM rpt.view_Sample;

DROP TABLE IF EXISTS rpt.mv_BET;
SELECT * INTO rpt.mv_BET FROM rpt.view_BET;

DROP TABLE IF EXISTS rpt.mv_Conductivity;
SELECT * INTO rpt.mv_Conductivity FROM rpt.view_Conductivity;

DROP TABLE IF EXISTS rpt.mv_FTIR;
SELECT * INTO rpt.mv_FTIR FROM rpt.view_FTIR;

DROP TABLE IF EXISTS rpt.mv_IGA;
SELECT * INTO rpt.mv_IGA FROM rpt.view_IGA;

DROP TABLE IF EXISTS rpt.mv_IGA_O;
SELECT * INTO rpt.mv_IGA_O FROM rpt.view_IGA_O;

DROP TABLE IF EXISTS rpt.mv_MetrologyRequest;
SELECT * INTO rpt.mv_MetrologyRequest FROM rpt.view_MetrologyRequest;

DROP TABLE IF EXISTS rpt.mv_PSA;
SELECT * INTO rpt.mv_PSA FROM rpt.view_PSA;

DROP TABLE IF EXISTS rpt.mv_Raman;
SELECT * INTO rpt.mv_Raman FROM rpt.view_Raman;

DROP TABLE IF EXISTS rpt.mv_SEMEDS;
SELECT * INTO rpt.mv_SEMEDS FROM rpt.view_SEMEDS;

DROP TABLE IF EXISTS rpt.mv_TGA;
SELECT * INTO rpt.mv_TGA FROM rpt.view_TGA;

DROP TABLE IF EXISTS rpt.mv_XRD;
SELECT * INTO rpt.mv_XRD FROM rpt.view_XRD;

DROP TABLE IF EXISTS rpt.mv_XRF;
SELECT * INTO rpt.mv_XRF FROM rpt.view_XRF;
